1. 导入 pandas，用字典创建 DataFrame：

   name: Tom, Jerry, Mike

   score: 85, 92, 78

   gender: 男，女，男

In [62]:
import pandas as pd
df1=pd.DataFrame({
    'name':['Tom','Jerry','Mike'],
    'score':[85,92,78],
    'gender':['男','女','男']
})
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

2. 查看上述 DataFrame 的前 1 行、形状、列名、数据类型。

In [63]:
df1.loc[0]

name      Tom
score      85
gender      男
Name: 0, dtype: object

In [64]:
df1.shape

(3, 3)

In [65]:
df1.columns

Index(['name', 'score', 'gender'], dtype='object')

In [66]:
type(df1)

pandas.core.frame.DataFrame

3. 用列表创建 DataFrame：

   data = [[1, "A"], [2, "B"], [3, "C"]]

   列名设为 id、tag

In [67]:
data = [[1, "A"], [2, "B"], [3, "C"]]
df2=pd.DataFrame(data,columns=['id','tag'])
df2

   id tag
0   1   A
1   2   B
2   3   C

### 二、列与行操作

1. 选取 score 和 gender 两列。

In [68]:
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [69]:
df1.score

0    85
1    92
2    78
Name: score, dtype: int64

In [70]:
df1.gender

0    男
1    女
2    男
Name: gender, dtype: object

2. 选取索引 0、2 的行。

In [71]:
df1.loc[[0,2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

3. 筛选 score>80 的行

In [83]:
df1[df1['score']>80]

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    良好

4. 新增一列 grade：score≥90 为优秀，否则为良好。

In [96]:
df1['grade']='良好'
df1.loc[df1['score']>=90,'grade']='优秀'
df1.grade

0    良好
1    优秀
2    良好
Name: grade, dtype: object

5. 删除 gender 列。

In [97]:
del df1['gender']

### 三、缺失值
1. 创建含缺失值的 DataFrame：

   data = {"x":[1, None, 3], "y":[None, 5, 6]}

   检测缺失值并统计每列缺失数量。

In [108]:
df2.isna()

       x      y
0  False   True
1   True  False
2  False  False

In [110]:
df2.isna().sum()

x    1
y    1
dtype: int64

2. 用 0 填充缺失值；删除含缺失值的行。

In [118]:
df2=df2.fillna(0)
df2

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

### 四、分组聚合

1. 按 gender 分组，求 score 的均值和最大值。

In [121]:
df1=pd.DataFrame({
    'name':['Tom','Jerry','Mike'],
    'score':[85,92,78],
    'gender':['男','女','男']
})
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [131]:
df1.groupby('gender')['score'].mean().sort_values(ascending=False)

gender
女    92.0
男    81.5
Name: score, dtype: float64

In [132]:
df1.groupby('gender')['score'].max().sort_values(ascending=False)

gender
女    92
男    85
Name: score, dtype: int64

2. 按 gender 分组，统计每组人数。

In [140]:
df1.groupby('gender').size()

gender
女    1
男    2
dtype: int64

### 五、排序与去重
1. 按 score 升序排序。

In [141]:
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [142]:
df1.sort_values('score',ascending=True)

    name  score gender
2   Mike     78      男
0    Tom     85      男
1  Jerry     92      女

2. 给 DataFrame 添加一行重复数据（如 Tom,85, 男），去重。

In [ ]:
df1.loc[len(df1)]=['Tom',85,'男']

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男
3    Tom     85      男
4    Tom     85      男

In [152]:
df1.drop_duplicates()

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

### 六、合并与拼接
1. 横向合并：

   df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})

   df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})

   按 id 合并

In [159]:
df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})
df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})
df3=pd.merge(df1,df2,on='id')
df3

   id name  age
0   1    X   20
1   2    Y   30

2. 纵向拼接：

   df_a = pd.DataFrame ({"val":[1,2]})

   df_b = pd.DataFrame ({"val":[3,4]})

   拼接后重置索引。

In [165]:
df3=pd.concat([df_a,df_b],ignore_index=True)
df3

   val
0    1
1    2
2    3
3    4

### 七、时间处理
1. 创建时间列：["2025-01-01","2025-01-02","2025-01-03"]，转为 datetime 格式

In [ ]:
df1=pd.DataFrame({'dt':["2025-01-01","2025-01-02","2025-01-03"]})
df1['dt']=pd.to_datetime(df1['dt'])

dt    datetime64[ns]
dtype: object

2. 提取时间列的月份、星期。

In [179]:
df1['年']=df1['dt'].dt.year
df1['月']=df1['dt'].dt.month
df1['日']=df1['dt'].dt.day
df1['星期']=df1['dt'].dt.day_name()
df1['周几']=df1['dt'].dt.weekday
df1

          dt     年  月  日         星期  周几
0 2025-01-01  2025  1  1  Wednesday   2
1 2025-01-02  2025  1  2   Thursday   3
2 2025-01-03  2025  1  3     Friday   4


### 八、高级操作

1. 对 score 列做标准化（(值 - 均值)/ 标准差）。

In [184]:
df1=pd.DataFrame({
    'name':['Tom','Jerry','Mike'],
    'score':[85,92,78],
    'gender':['男','女','男']
})
mean=df1['score'].mean()
std=df1['score'].std()
df1['标准化成绩']=(df1['score']-mean)/std
df1

    name  score gender  标准化成绩
0    Tom     85      男    0.0
1  Jerry     92      女    1.0
2   Mike     78      男   -1.0

2. 用透视表：行是 gender，值是 score，聚合函数为中位数。

In [191]:
pd.pivot_table(
    data=df1,
    index='gender',
    values='score',
    aggfunc=['median','max','mean']
)

       median   max  mean
        score score score
gender
女        92.0    92  92.0
男        81.5    85  81.5